# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

## Topics Covered

This notebook covers fundamental linear algebra concepts essential for machine learning:

* **Vector Operations**: Basic arithmetic with vectors (scaling, addition, element-wise multiplication)
* **Multiplication**: 
    * Vector-vector multiplication (dot product)
    * Matrix-vector multiplication 
    * Matrix-matrix multiplication
* **Identity Matrix**: The equivalent of 1 in matrix algebra
* **Inverse**: Matrix operations to reverse multiplication effects

In [1]:
import numpy as np

### Setting up NumPy

We'll use NumPy for efficient linear algebra operations. NumPy provides optimized implementations of vector and matrix operations.

## Vector Operations

### What is a Vector?

A vector is a one-dimensional array of numbers. We can perform basic arithmetic operations on vectors:
- **Scalar multiplication**: Multiply each element by a number
- **Vector addition**: Add corresponding elements of two vectors
- **Element-wise multiplication**: Multiply corresponding elements (also called Hadamard product)

In [ ]:
# Create a 1D vector
u = np.array([2, 4, 5, 6])

In [ ]:
# Scalar multiplication: multiply each element by 2
2 * u

array([ 4,  8, 10, 12])

In [ ]:
# Create another vector
v = np.array([1, 0, 0, 2])

In [ ]:
# Vector addition: add corresponding elements
u + v

array([3, 4, 5, 8])

In [ ]:
# Element-wise multiplication (Hadamard product): multiply corresponding elements
u * v

array([ 2,  0,  0, 12])

## Multiplication

### Vector-Vector Multiplication (Dot Product)

The dot product combines two vectors into a single scalar. It's calculated as:
$$\mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i \cdot v_i$$

The dot product is fundamental in machine learning for computing predictions and similarities between vectors.

In [ ]:
# Check the length of vector v
v.shape[0]

4

In [ ]:
def vector_vector_multiplication(u, v):
    """
    Calculate the dot product of two vectors.
    
    Parameters:
    u, v: 1D numpy arrays of the same length
    
    Returns:
    A scalar value representing the sum of element-wise products
    """
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    # Sum the product of each pair of elements
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [ ]:
# Compute dot product using our custom implementation
vector_vector_multiplication(u, v)

14.0

In [13]:
u.dot(v)

14

Compare with NumPy's built-in `.dot()` method - same result but optimized:

In [ ]:
# Create a 2D matrix with 3 rows and 4 columns
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

### Matrix-Vector Multiplication

When multiplying a matrix by a vector, each row of the matrix is multiplied with the vector (dot product), resulting in a new vector.

For a matrix **U** of shape (m, n) and vector **v** of shape (n,):
$$\text{Result}_i = \text{sum}(\text{U}_i \cdot \mathbf{v})$$

The result is a vector of shape (m,).

In [ ]:
# Check the shape: 3 rows and 4 columns
U.shape

(3, 4)

In [ ]:
def matrix_vector_multiplication(U, v):
    """
    Multiply a matrix by a vector.
    
    Parameters:
    U: 2D numpy array of shape (m, n)
    v: 1D numpy array of shape (n,)
    
    Returns:
    A 1D numpy array of shape (m,) where each element is the dot product 
    of the corresponding row of U with v
    """
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    # Initialize result vector with zeros
    result = np.zeros(num_rows)
    
    # For each row in the matrix, compute dot product with vector v
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [ ]:
# Compute matrix-vector product using our custom implementation
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [19]:
U.dot(v)

array([14,  5,  5])

Using NumPy's optimized `.dot()` method - produces identical results:

In [ ]:
# Create a second matrix with 4 rows and 3 columns
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

### Matrix-Matrix Multiplication

Multiplying two matrices produces a new matrix. For matrices **U** (shape m×n) and **V** (shape n×k):
$$\text{Result}_{i,j} = \sum_{p=1}^{n} U_{i,p} \cdot V_{p,j}$$

Each element in the result is the dot product of a row from **U** with a column from **V**. The result has shape (m×k).

In [ ]:
def matrix_matrix_multiplication(U, V):
    """
    Multiply two matrices.
    
    Parameters:
    U: 2D numpy array of shape (m, n)
    V: 2D numpy array of shape (n, k)
    
    Returns:
    A 2D numpy array of shape (m, k) where each element [i,j] is the dot product
    of row i of U with column j of V
    """
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    # Initialize result matrix with zeros
    result = np.zeros((num_rows, num_cols))
    
    # For each column in V, multiply U by that column and store in result
    for i in range(num_cols):
        vi = V[:, i]  # Extract the i-th column from V
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [ ]:
# Compute matrix-matrix product using our custom implementation
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [23]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

NumPy's optimized `.dot()` method produces the same result:

## Identity Matrix

The identity matrix is the equivalent of "1" in matrix algebra. When you multiply any matrix by the identity matrix, you get the original matrix back.

For an n×n identity matrix **I**:
- Diagonal elements = 1
- All other elements = 0

Key property: **A** × **I** = **A** and **I** × **A** = **A**

In [ ]:
# Create a 3x3 identity matrix
I = np.eye(3)

In [ ]:
# Display matrix V (first 3 rows form a square matrix)
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
# Multiply matrix V by the identity matrix - result should be V itself
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

The inverse of a matrix **A** (denoted **A**⁻¹) is a matrix that, when multiplied by **A**, gives the identity matrix:
$$\mathbf{A} \times \mathbf{A}^{-1} = \mathbf{I}$$

**Important**: 
- Only square matrices can have inverses
- Not all square matrices are invertible (must be non-singular)
- The inverse is useful for solving linear equations: if **Ax** = **b**, then **x** = **A**⁻¹**b**

In [ ]:
# Extract first 3 rows of V to form a square matrix (3x3)
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [ ]:
# Compute the inverse of the square matrix using NumPy
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [ ]:
# Verify the inverse property: Vs_inv × Vs should equal the identity matrix
# (Note: Due to floating point precision, values very close to 0 and 1 are expected)
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Summary

You now understand the fundamental linear algebra operations used in machine learning:

1. **Vector Operations**: Scaling, addition, and element-wise multiplication
2. **Dot Product**: Combines two vectors into a scalar (vector-vector multiplication)
3. **Matrix-Vector Multiplication**: Transforms a vector using a matrix
4. **Matrix-Matrix Multiplication**: Combines two matrices (core of neural networks)
5. **Identity Matrix**: The multiplicative identity for matrices
6. **Matrix Inverse**: The opposite operation, useful for solving linear systems

These concepts form the mathematical foundation for understanding:
- Linear regression
- Neural networks
- Dimensionality reduction
- Optimization algorithms

### Next Step
Introduction to Pandas for data manipulation and analysis

In [ ]:
# Additional resources and practice
# Try modifying the vectors and matrices above and observing how operations change
# Experiment with different vector sizes and matrix dimensions